### PR TITLE
Update unsupported commands test to handle command status response

### PR DESCRIPTION
**Pull request by joerchan**
Update unsupported commands test to handle receiving an unknown
command response from either command complete or command status event.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@heri-developer Will you update the zephyr mirror and the zephyr manifest as well?

**Comment by heri-developer** [comment]
We will update the mirror.  You must update the manifest.

**Comment by wopu-ot** [comment]
Updating the manifest could/should be part of https://github.com/zephyrproject-rtos/zephyr/pull/24380

**Comment by joerchan** [comment]
Ok. thanks both. I will update the manifest once the mirror is available.

**Pull request merged**
