### PR TITLE
Fix use of invalid disconnect reason in test procedures

### PR DESCRIPTION
**Pull request by joerchan**
Fix use of the invalid disconnect reason 0x3e "connection failed to
be established", which is not valid in the Disconnect command.
Use the more appropriate reason 0x13 "remote user terminated
connection"

Update for GAP, GATT and HCI test cases, LL has already been updated.

Follow up to : https://github.com/EDTTool/EDTT/pull/20

### CODE REVIEW

**Review by heri-developer — APPROVED** [review]

**Comment by joerchan** [comment]
@heri-developer Should I add more reviewers here?
Also I cannot update zephyr PR `pull/23/head` because of different remotes. But I have run all of these tests locally and they all pass.

**Comment by heri-developer** [comment]
For this kind of change - I think it is fine.

**Comment by joerchan** [comment]
@heri-developer Thanks. Can you let me know when this change has been pushed to https://github.com/zephyrproject-rtos/edtt?

**Comment by wopu-ot** [comment]
@joerchan Change is pushed

**Comment by aescolar** [comment]
@joerchan
> Can you let me know when this change has been pushed to

Just FYI: The mirroring is automatic and takes a couple of minutes (<15m).

> Also I cannot update zephyr PR

For a Zephyr PR to point to a separate repo for testing, you just need to add a new remote to the list in the top, and then add a remote line in the particular repo.

**Comment by joerchan** [comment]
@aescolar Thank you. I didn't know that the process was automatic.

**Pull request merged**
