### PR TITLE
EDTT: updated DLE test criteria

### PR DESCRIPTION
**Pull request by kruithofa**
Minimum acceptable value for DLE time calculations is 328 instead of 592

### CODE REVIEW

**Comment by kruithofa** [comment]
> Thanks Andries, but remember you need to sign-off the commit
> A small description in the commit body (say just what you wrote in the PR description) would be very nice to add.

Mea culpa
Description and sign-off added

**Comment by aescolar** [comment]
Thanks @kruithofa, but how is your signed-off line not "Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>" ?

**Comment by aescolar** [comment]
CI run with this PR and 
https://github.com/zephyrproject-rtos/zephyr/pull/23046
LL/CON/SLA/BV-77-C seems to be failing :(
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/64217/1/console 
@kruithofa

**Comment by kruithofa** [comment]
> Note failing test

Fixed failing test

**Comment by aescolar** [comment]
@kruithofa It does indeed seem to pass now. Thanks :)

**Pull request merged**
